GamingSite/GamingSite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main_page, name='main'),
    path('admin/', admin.site.urls),
    path('games/', include('games.urls'), name='games'),
    path('polls/', include('polls.urls'), name='polls'),
    path('profile/', include('profile.urls'), name='profile'),
    path('common/', include('common.urls'), name='common'),
]

GamingSite/games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('othello/', views.othello_lobby, name='othello'),
    path('othello/ai/<int:room_id>/<str:player>/', views.othello_ai, name='othello_ai'),
    path('othello/<int:room_id>/<str:player>/', views.othello_player, name='othello_player'),
    path('tictactoe/', views.tictactoe, name='tictactoe'),
    path('tictactoe/ai/<int:room_id>/', views.tictactoe_ai, name='tictactoe_ai'),
    path('tictactoe/X/<int:room_id>/', views.tictactoe_x, name='tictactoe_X'),
    path('tictactoe/O/<int:room_id>/', views.tictactoe_o, name='tictactoe_O'),
    path('ganz-schon-clever/', views.ganz, name='ganz'),
]

GamingSite/games/models.py
from django.db import models
from . import support as sup
from . import ai_minimax as aim
from . import ai_greedy as aig
from . import ai_improved as aii
from . import ai_tic as ait
import copy


class GamesList(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    create_date = models.DateTimeField()

    def __str__(self):
        return self.name


class GameTicTacToe:
    def __init__(self, room_id):
        self.room_id = room_id
        self.board = [['0', '1', '2'], ['3', '4', '5'], ['6', '7', '8']]
        self.turn = 'X'
        self.valid = {(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)}
        self.end = False
        self.ai = self.room_id % 2 == 1

    def initialize(self):
        self.board = [['0', '1', '2'], ['3', '4', '5'], ['6', '7', '8']]
        self.turn = 'X'
        self.valid = {(0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)}
        self.end = False
        self.ai = self.room_id % 2 == 1

    def is_game_over(self):
        for i in range(3):
            if self.board[i][0] == self.board[i][1] == self.board[i][2]:
                if self.board[i][0] == 'X':
                    return 'X'
                else:
                    return 'O'
        for j in range(3):
            if self.board[0][j] == self.board[1][j] == self.board[2][j]:
                if self.board[0][j] == 'X':
                    return 'X'
                else:
                    return 'O'
        if self.board[0][0] == self.board[1][1] == self.board[2][2]:
            if self.board[0][0] == 'X':
                return 'X'
            else:
                return 'O'
        if self.board[0][2] == self.board[1][1] == self.board[2][0]:
            if self.board[0][2] == 'X':
                return 'X'
            else:
                return 'O'
        if self.valid:
            return False
        else:
            return "Draw"

    def update(self, action):
        if not self.end:
            c = (action // 3, action % 3)
            if c in self.valid:
                self.valid.remove(c)
                self.board[c[0]][c[1]] = self.turn
                if self.turn == 'X':
                    self.turn = 'O'
                else:
                    self.turn = 'X'
                self.end = self.is_game_over()
                self.ai = True

    def play_ai_dumb(self):
        if not self.end:
            action = ait.dumb(list(self.valid))
            self.valid.remove(action)
            self.board[action[0]][action[1]] = self.turn
            if self.turn == 'X':
                self.turn = 'O'
            else:
                self.turn = 'X'
            self.end = self.is_game_over()
        self.ai = False

    def play_ai_minimax(self):
        if not self.end:
            action = ait.minimax(self.board, list(self.valid), self.turn)
            self.valid.remove(action)
            self.board[action[0]][action[1]] = self.turn
            if self.turn == 'X':
                self.turn = 'O'
            else:
                self.turn = 'X'
            self.end = self.is_game_over()
        self.ai = False


class GameOthello:
    def __init__(self, room_id):
        self.room_id = room_id
        self.depth_medium = 5
        self.depth_hard = 4
        self.rou = 0         # round
        self.board = sup.Board()  # initialize the game board
        self.memo = {self.rou: copy.deepcopy(self.board)}  # save previous states of the game
        self.v = {20: [28], 29: [28], 34: [35], 43: [35]}  # set of valid moves (initial state)
        self.end = False  # becomes color of the winner when the game ends
        self.ai = 0
        if (self.room_id % 4) >= 2:
            self.update(20)
            self.ai = 0

    def initialize(self):
        self.rou = 0  # round
        self.board = sup.Board()  # initialize the game board
        self.memo = {self.rou: copy.deepcopy(self.board)}  # save previous states of the game
        self.v = {20: [28], 29: [28], 34: [35], 43: [35]}  # set of valid moves (initial state)
        self.end = False  # becomes color of the winner when the game ends
        if (self.room_id % 4) >= 2:
            self.update(20)
        self.ai = 0

    def prepare_next_round(self):
        self.v = sup.valid(self.board.b, 129 - self.board.turn)
        if self.v:
            self.board.turn = 129 - self.board.turn
            self.memo[self.rou] = copy.deepcopy(self.board)
            self.ai = 1 - self.ai
        else:
            self.v = sup.valid(self.board.b, self.board.turn)
            self.memo[self.rou] = copy.deepcopy(self.board)
            if not self.v:
                if self.board.wn > self.board.bn:
                    self.end = "White"
                elif self.board.wn < self.board.bn:
                    self.end = "Black"
                else:
                    self.end = "Draw"
                self.ai = 0
                self.board.turn = 129 - self.board.turn

    def back(self):
        while self.rou > 0:
            self.rou -= 1
            if self.memo[self.rou].turn == self.board.turn:
                break
        self.board = copy.deepcopy(self.memo[self.rou])
        self.v = sup.valid(self.board.b, self.board.turn)

    def update(self, action):
        if not self.end:
            if action in self.v:
                self.board.flip(action, self.v[action])
                self.rou += 1
                self.prepare_next_round()

    def play_ai_greedy(self):
        if not self.end:
            z = aig.pick(self.board.b, self.board.wn, self.board.bn, self.board.turn, self.v, 0)
            self.board.flip(z, self.v[z])
            self.rou += 1
            self.prepare_next_round()

    def play_ai_minimax(self):
        if not self.end:
            z = aim.pick(self.board.b, self.board.wn, self.board.bn, self.board.turn, self.v, self.depth_medium)
            self.board.flip(z, self.v[z])
            self.rou += 1
            self.prepare_next_round()

    def play_ai_improved(self):
        if not self.end:
            z = aii.pick(self.board.b, self.board.wn, self.board.bn, self.board.turn, self.v, self.depth_hard)
            self.board.flip(z, self.v[z])
            self.rou += 1
            self.prepare_next_round()

GamingSite/games/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.safestring import mark_safe
from django.template import loader
from django.urls import reverse
import json
from .models import GameTicTacToe, GameOthello, GamesList

tictactoe_models = [GameTicTacToe(i) for i in range(7)]
othello_models = [GameOthello(i) for i in range(16)]


def main_page(request):
    list_of_game = GamesList.objects.order_by("-create_date")
    context = {"games": list_of_game}
    return render(request, "games/main.html", context=context)


def othello_lobby(request):
    return render(request, "games/othello/othello_lobby.html")


def othello_ai(request, room_id, player):
    context = {"model": othello_models[room_id], "player": player, "room_id": room_id}
    return render(request, "games/othello/othello_ai.html", context=context)


def othello_player(request, room_id, player):
    context = {"model": othello_models[room_id], "player": player, "room_id": room_id}
    return render(request, "games/othello/othello_player.html", context=context)


def tictactoe(request):
    return render(request, "games/tic-tac-toe/tic-tac-toe_main.html")


def tictactoe_ai(request, room_id):
    model = tictactoe_models[room_id]
    if model.ai:
        if room_id < 2:
            model.play_ai_dumb()
        else:
            model.play_ai_minimax()
        return render(request, "games/tic-tac-toe/tic-tac-toe_player.html", context={"model": model})
    else:
        if request.method == "POST":
            z = int(request.POST.get("action"))
            print(z)
            if z == -2:
                model.initialize()
            else:
                model.update(z)
        return render(request, "games/tic-tac-toe/tic-tac-toe_ai.html", context={"model": model})


def tictactoe_x(request, room_id):
    model = tictactoe_models[room_id]
    if model.turn == 'X':
        if request.method == "POST":
            z = int(request.POST.get("action"))
            print(z)
            if z == -2:
                model.initialize()
            else:
                model.update(z)
            return render(request, "games/tic-tac-toe/tic-tac-toe_waiting.html", context={"model": model})
        else:
            return render(request, "games/tic-tac-toe/tic-tac-toe.html", context={"model": model})
    else:
        return render(request, "games/tic-tac-toe/tic-tac-toe_waiting.html", context={"model": model})


def tictactoe_o(request, room_id):
    model = tictactoe_models[room_id]
    if model.turn == 'O':
        if request.method == "POST":
            z = int(request.POST.get("action"))
            print(z)
            if z == -2:
                model.initialize()
            else:
                model.update(z)
            return render(request, "games/tic-tac-toe/tic-tac-toe_waiting.html", context={"model": model})
        else:
            return render(request, "games/tic-tac-toe/tic-tac-toe.html", context={"model": model})
    else:
        return render(request, "games/tic-tac-toe/tic-tac-toe_waiting.html", context={"model": model})


def ganz(request):
    return render(request, "games/ganz-schon-clever/ganz-schon-clever.html")

GamingSite/templates/games/tic-tac-toe/tic-tac-toe.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'board_styles.css' %}">
    <title>Tic Tac Toe</title>
</head>
<body>
{% include "navbar.html" %}
<form id="action" method="POST" class="board" style="width: 210px;">
  {% csrf_token %}
  {% if model.end %}
    {% if model.end == 'Draw' %}
        <h1>Draw!</h1>
    {% else %}
        <h1>{{ model.end }} has won the game!</h1>
    {% endif %}
  {% else %}
    <h1>{{ model.turn }}'s turn</h1>
  {% endif %}
  {% for row in model.board %}
  <div class="row" style="line-height: 65px;">
    {% for element in row %}
      {% if element == 'O' or element == 'X' %}
        <div class="square" style="font-size: 80px;">{{ element }}</div>
      {% else %}
        <button name="action" type="submit" value="{{ element }}" class="square"></button>
      {% endif %}
    {% endfor %}
  </div>
  {% endfor %}
  <div class="row">
    <div class="col-12">
      <button name="action" type="submit" value="-2" class="btn btn-outline-danger btn-lg" style="margin: 20px;">restart</button>
    </div>
  </div>
</form>
<button class="btn btn-outline-primary btn-lg" style="margin: 10px;">
  <a href="../../">Back to the room list</a>
</button>
</body>
</html>

GamingSite/templates/games/tic-tac-toe/tic-tac-toe_ai.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="refresh" content="1; url={% url 'games:tictactoe_ai' model.room_id  %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'board_styles.css' %}">
    <title>Tic Tac Toe</title>
</head>
<body>
{% include "navbar.html" %}
<form id="action" method="POST" class="board" style="width: 210px;">
  {% csrf_token %}
  {% if model.end %}
    {% if model.end == 'Draw' %}
        <h1>Draw!</h1>
    {% else %}
        <h1>{{ model.end }} has won the game!</h1>
    {% endif %}
  {% else %}
    <h1>{{ model.turn }}'s turn</h1>
  {% endif %}
  {% for row in model.board %}
  <div class="row" style="line-height: 65px;">
    {% for element in row %}
      {% if element == 'O' or element == 'X' %}
        <div class="square" style="font-size: 80px;">{{ element }}</div>
      {% else %}
        <button name="action" type="submit" value="{{ element }}" class="square"></button>
      {% endif %}
    {% endfor %}
  </div>
  {% endfor %}
  <div class="row">
    <div class="col-12">
      <button name="action" type="submit" value="-2" class="btn btn-outline-danger btn-lg" style="margin: 20px;">restart</button>
    </div>
  </div>
</form>
<button class="btn btn-outline-primary btn-lg" style="margin: 10px;">
  <a href="../../">Back to the room list</a>
</button>
</body>
</html>

GamingSite/templates/games/tic-tac-toe/tic-tac-toe_main.html
{% extends 'base.html' %}
{% block content %}
<table class="table table-bordered" style="border: 5px solid black; margin: 5px; width: 650px; text-align: center;">
    <thead style="background: silver; border: 3px solid gray">
        <tr>
            <th colspan="2" style="font-size: 25px; text-align: center;">Opponent</th>
            <th style="font-size: 25px; text-align: center;">Room No.</th>
            <th colspan="2" style="font-size: 25px; text-align: center;">Symbol</th>
        </tr>
    </thead>
    <tbody>
    <tr>
        <td rowspan="4" style="background: lightblue; font-size: 30px; width: 200px; vertical-align: middle;">vs AI</td>
        <td rowspan="2" style="background: yellowgreen; font-size: 20px; width: 150px; vertical-align: middle;">dumb AI<br>(random)</td>
        <td>Room 0</td>
        <td style="width: 75px;"><a href="ai/0">X</a></td>
        <td style="width: 75px;"></td>
    </tr>
    <tr>
        <td>Room 1</td>
        <td></td>
        <td><a href="ai/1">O</a></td>
    </tr>
    <tr>
        <td rowspan="2" style="background: pink; font-size: 20px; vertical-align: middle;">minimax AI</td>
        <td>Room 2</td>
        <td><a href="ai/2">X</a></td>
        <td></td>
    </tr>
    <tr>
        <td>Room 3</td>
        <td></td>
        <td><a href="ai/3">O</a></td>
    </tr>
    <tr>
        <td colspan="2" rowspan="3" style="background: crimson; font-size: 30px; vertical-align: middle;">Duel</td>
        <td>Room 4</td>
        <td><a href="X/4">X</a></td>
        <td><a href="O/4">O</a></td>
    </tr>
    <tr>
        <td>Room 5</td>
        <td><a href="X/5">X</a></td>
        <td><a href="O/5">O</a></td>
    </tr>
    <tr>
        <td>Room 6</td>
        <td><a href="X/6">X</a></td>
        <td><a href="O/6">O</a></td>
    </tr>
    </tbody>
</table>
<button type="button" class="btn btn-outline-dark btn-lg" style="margin: 5px;">
    <a href="../">Back to the game list</a>
</button>
{% endblock %}

GamingSite/templates/games/tic-tac-toe/tic-tac-toe_player.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'board_styles.css' %}">
    <title>Tic Tac Toe</title>
</head>
<body>
{% include "navbar.html" %}
<form id="action" method="POST" class="board" style="width: 210px;">
  {% csrf_token %}
  {% if model.end %}
    {% if model.end == 'Draw' %}
        <h1>Draw!</h1>
    {% else %}
        <h1>{{ model.end }} has won the game!</h1>
    {% endif %}
  {% else %}
    <h1>{{ model.turn }}'s turn</h1>
  {% endif %}
  {% for row in model.board %}
  <div class="row" style="line-height: 65px;">
    {% for element in row %}
      {% if element == 'O' or element == 'X' %}
        <div class="square" style="font-size: 80px;">{{ element }}</div>
      {% else %}
        <button name="action" type="submit" value="{{ element }}" class="square"></button>
      {% endif %}
    {% endfor %}
  </div>
  {% endfor %}
  <div class="row">
    <div class="col-12">
      <button name="action" type="submit" value="-2" class="btn btn-outline-danger btn-lg" style="margin: 20px;">restart</button>
    </div>
  </div>
</form>
<button class="btn btn-outline-primary btn-lg" style="margin: 10px;">
  <a href="../../">Back to the room list</a>
</button>
</body>
</html>

GamingSite/templates/games/tic-tac-toe/tic-tac-toe_waiting.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="refresh" content="1">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'board_styles.css' %}">
    <title>Tic Tac Toe</title>
</head>
<body>
{% include "navbar.html" %}
<form id="action" method="POST" class="board" style="width: 210px;">
  {% csrf_token %}
  {% if model.end %}
    {% if model.end == 'Draw' %}
        <h1>Draw!</h1>
    {% else %}
        <h1>{{ model.end }} has won the game!</h1>
    {% endif %}
  {% else %}
    <h1>{{ model.turn }}'s turn</h1>
  {% endif %}
  {% for row in model.board %}
  <div class="row" style="line-height: 65px;">
    {% for element in row %}
      {% if element == 'O' or element == 'X' %}
        <div class="square" style="font-size: 80px;">{{ element }}</div>
      {% else %}
        <button name="action" type="submit" value="{{ element }}" class="square"></button>
      {% endif %}
    {% endfor %}
  </div>
  {% endfor %}
  <div class="row">
    <div class="col-12">
      <button name="action" type="submit" value="-2" class="btn btn-outline-danger btn-lg" style="margin: 20px;">restart</button>
    </div>
  </div>
</form>
<button class="btn btn-outline-primary btn-lg" style="margin: 10px;">
  <a href="../../">Back to the room list</a>
</button>
</body>
</html>