GamingSite/GamingSite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main_page, name='main'),
    path('admin/', admin.site.urls),
    path('games/', include('games.urls'), name='games'),
    path('polls/', include('polls.urls'), name='polls'),
    path('profile/', include('profile.urls'), name='profile'),
    path('common/', include('common.urls'), name='common'),
]

GamingSite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.sign_up, name='signup')
]

GamingSite/games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('othello/', views.othello_lobby, name='othello'),
    path('othello/ai/<int:room_id>/<str:player>/', views.othello_ai, name='othello_ai'),
    path('othello/<int:room_id>/<str:player>/', views.othello_player, name='othello_player'),
    path('tictactoe/', views.tictactoe, name='tictactoe'),
    path('tictactoe/ai/<int:room_id>/', views.tictactoe_ai, name='tictactoe_ai'),
    path('tictactoe/X/<int:room_id>/', views.tictactoe_x, name='tictactoe_X'),
    path('tictactoe/O/<int:room_id>/', views.tictactoe_o, name='tictactoe_O'),
    path('ganz-schon-clever/', views.ganz, name='ganz'),
]

GamingSite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
]

GamingSite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'board_styles.css' %}">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Welcome!</title>
</head>
<body>
{% include "navbar.html" %}
{% block content %}
{% endblock %}
</body>
</html>

GamingSite/templates/login_error.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ error }}
        </div>
    {% endfor %}
{% endif %}

GamingSite/templates/main.html
{% extends 'base.html' %}
{% block content %}
<div class="card" style="width: 36rem">
    <div class="card-body">
        <h4 style="margin-bottom: 20px;">About the developer</h4>
        <p><a href="/profile">See profile</a></p>
    </div>
</div>
<div class="card" style="width: 36rem">
    <div class="card-body">
        <h5 class="card-title">Play Games</h5>
        <h6 class="card-subtitle mb-2 text-muted">Othello, Tic-Tac-Toe, Ganz Schön Clever</h6>
        <p class="card-text">I hope you can enjoy these games!</p>
        <a href="/games" class="card-link">Join!</a>
    </div>
</div>
<div class="card" style="float: left; width: 18rem">
    <div class="card-body"><a href="/polls">Give answers to the polls</a></div>
</div>
<div class="card" style="float: left; width: 18rem">
    <div class="card-body"><a href="/admin">For administrator</a></div>
</div>
{% endblock %}

GamingSite/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-top">
    <a class="navbar-brand" href="{% url 'main' %}">Gaming Site</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbar_games">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'games:main' %}">Games</a>
            </li>
        </ul>
    </div>
    <div class="collapse navbar-collapse flex-grow-0" id="navbar_polls">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:index' %}">Polls</a>
            </li>
        </ul>
    </div>
    <div class="collapse navbar-collapse flex-grow-0" id="navbar_login">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (Logout)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">Login</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>