GamingSite/GamingSite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main_page, name='main'),
    path('admin/', admin.site.urls),
    path('games/', include('games.urls'), name='games'),
    path('polls/', include('polls.urls'), name='polls'),
    path('profile/', include('profile.urls'), name='profile'),
    path('common/', include('common.urls'), name='common'),
]

GamingSite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.sign_up, name='signup')
]

GamingSite/games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('othello/', views.othello_lobby, name='othello'),
    path('othello/ai/<int:room_id>/<str:player>/', views.othello_ai, name='othello_ai'),
    path('othello/<int:room_id>/<str:player>/', views.othello_player, name='othello_player'),
    path('tictactoe/', views.tictactoe, name='tictactoe'),
    path('tictactoe/ai/<int:room_id>/', views.tictactoe_ai, name='tictactoe_ai'),
    path('tictactoe/X/<int:room_id>/', views.tictactoe_x, name='tictactoe_X'),
    path('tictactoe/O/<int:room_id>/', views.tictactoe_o, name='tictactoe_O'),
    path('ganz-schon-clever/', views.ganz, name='ganz'),
]

GamingSite/common/models.py
from django.db import models

# Create your models here.

GamingSite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="e-mail")

    class Meta:
        model = User
        fields = ("username", "email")

GamingSite/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import UserForm


def sign_up(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect("main")
    else:
        form = UserForm()
    return render(request, "common/sign_up.html", {"form": form})

GamingSite/templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>Log In</h4>
        </div>
        <div class="col-8 text-right">
            <span><a href="{% url 'common:signup' %}">Sign Up</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="">
        {% csrf_token %}
        {% include "login_error.html" %}
        <div class="form-group">
            <label for="username">ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">password</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">login</button>
    </form>
</div>
{% endblock %}

GamingSite/templates/common/sign_up.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>Sign Up</h4>
        </div>
        <div class="col-8 text-right">
            <span><a href="{% url 'common:login' %}">Log In</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "login_error.html" %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">Verify Password</label>
            <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">E-mail</label>
            <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
</div>
{% endblock %}