GamingSite/GamingSite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.main_page, name='main'),
    path('admin/', admin.site.urls),
    path('games/', include('games.urls'), name='games'),
    path('polls/', include('polls.urls'), name='polls'),
    path('profile/', include('profile.urls'), name='profile'),
    path('common/', include('common.urls'), name='common'),
]

GamingSite/games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('othello/', views.othello_lobby, name='othello'),
    path('othello/ai/<int:room_id>/<str:player>/', views.othello_ai, name='othello_ai'),
    path('othello/<int:room_id>/<str:player>/', views.othello_player, name='othello_player'),
    path('tictactoe/', views.tictactoe, name='tictactoe'),
    path('tictactoe/ai/<int:room_id>/', views.tictactoe_ai, name='tictactoe_ai'),
    path('tictactoe/X/<int:room_id>/', views.tictactoe_x, name='tictactoe_X'),
    path('tictactoe/O/<int:room_id>/', views.tictactoe_o, name='tictactoe_O'),
    path('ganz-schon-clever/', views.ganz, name='ganz'),
]

GamingSite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
]

GamingSite/polls/models.py
from django.db import models
from django import forms


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    a1 = models.IntegerField(default=0)
    a2 = models.IntegerField(default=0)
    a3 = models.IntegerField(default=0)
    a4 = models.IntegerField(default=0)
    a5 = models.IntegerField(default=0)
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(forms.Form):
    answer = forms.IntegerField()


GamingSite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from django.urls import reverse
from .models import Question
from django.utils import timezone


def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'polls/question_page.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    z = question.content.split('\r\n')
    context = {'question': question, 'z': z, 'total': question.a1 + question.a2 + question.a3 + question.a4 + question.a5}
    return render(request, 'polls/question_detail.html', context)


def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    q = int(request.POST.get("answer"))
    if q == 1:
        question.a1 += 1
    elif q == 2:
        question.a2 += 1
    elif q == 3:
        question.a3 += 1
    elif q == 4:
        question.a4 += 1
    else:
        question.a5 += 1
    question.save()
    return redirect('polls:detail', question_id=question_id)

GamingSite/templates/polls/question_detail.html
{% extends 'base.html' %}
{% block content %}
<body>
<div class="container my-3" style="border: 10px double black; padding: 60px;">
<div class="container my-3" style="border: 2px solid black;">
    <h2 style="text-align: center;">{{ question.subject }}</h2>
</div>
<div class="container my-3" style="font-size: 25px; background: ivory; border: 2px dashed gray">
    <p style="font-weight: 500;">
        {% if total == 0 %}
        There is no answer.
        {% elif total == 1 %}
        There is 1 answer.
        {% else %}
        There are {{ total }} answers.
        {% endif %}
    </p>
    <canvas id="pieChart" style="background: ivory;"></canvas>
</div>
<div class="container my-3" style="font-size: 20px; background: ivory;">
<form action="{% url 'polls:answer_create' question.id %}" method="post">
    {% csrf_token %}
    {% for zz in z %}
    <p><label><input type="radio" name="answer" value="{{ forloop.counter }}">{{ zz }}</label></p>
    {% endfor %}
    <input type="submit" value="Register Answer">
</form>
</div>
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
    var answers = new Array();
    {% for zz in z %}
        answers.push("{{ zz }}");
    {% endfor %}
    var ctxP = document.getElementById("pieChart").getContext('2d');
    var myPieChart = new Chart(ctxP, {
        type: 'pie',
        data: {
            labels: answers,
            datasets: [{
                data: [{{ question.a1 }}, {{ question.a2 }}, {{ question.a3 }}, {{ question.a4 }}, {{ question.a5 }}],
                backgroundColor: ["#F7464A", "#46BFBD", "#FDB45C", "#949FB1", "#4D5360"],
                hoverBackgroundColor: ["#FF5A5E", "#5AD3D1", "#FFC870", "#A8B3C5", "#616774"]
            }]
        },
        options: {responsive: true}
    });
</script>
{% endblock %}

GamingSite/templates/polls/question_page.html
{% extends 'base.html' %}
{% block content %}
<table class="table">
    <thead>
    <tr class="thead-dark">
        <th>No</th>
        <th>Subject</th>
        <th>Date</th>
    </tr>
    </thead>
    <tbody>
    {% if question_list %}
    {% for question in question_list %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'polls:detail' question.id %}">{{ question.subject }}</a></td>
        <td>{{ question.create_date }}</td>
    </tr>
    {% endfor %}
    {% else %}
    <tr>
        <td>0</td>
        <td>there is no question.</td>
        <td>None</td>
    </tr>
    {% endif %}
    </tbody>
</table>
<button type="button" class="button-89" style="margin: 10px;">
    <a href="../" style="font-size: 20px;">Back to main page</a>
</button>
{% endblock %}